### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "i -> P(r)"
keywords:    "technology, incubator, startups"
description: "Increasing probability of a better future"
source_link: "http://opsbug.com/tech-inoculator"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-51452705-10 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
